config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users

  resources :customers, only: [:new, :create, :show]

  resources :projects, only: [:new, :create]

  resources :tasks

end

app/models/customer.rb
class Customer < ActiveRecord::Base

    has_many :projects
    has_many :tasks, through: :projects

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :tasks
	belongs_to :customer
    
end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :project
	has_many :task_entries
	has_many :tasks, through: :task_entries
    
end

app/models/task_entry.rb
class TaskEntry < ActiveRecord::Base

    belongs_to :user
    belongs_to :task
    
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
	has_many :task_entries
    has_many :tasks, through: :task_entries
    has_many :projects
    has_many :projects, through: :tasks
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
        redirect_to '/login' unless current_user
    end
    
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	before_filter :authorize

	def new
		@customer = Customer.new
	end

	def create
		@customer = Customer.new(customer_params)
		if @customer.save
			redirect_to user
		else
			redirect_to user
		end
	end

	private

	def customer_params
		params.require(:customer).permit(:name, :address_1, :address_2, :address_3, :city, :state, :zip, :phone_1, :phone_2, :fax_1, :fax_2, :email, :website)
	end
	
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
	before_filter :authorize
	before_action :set_user, except: [:show]

	def index
		@horses = @user.horses.all
	end

	def new
		@horse = Horse.new
	end

	def create
		@horse = @user.horses.new(horse_params)
		if @horse.save
			redirect_to user_horses_path
		else
			redirect_to new_user_horse_path
		end
	end

	def show
		@horse = Horse.find_by id: params[:id]
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private

	def set_user
		@user = User.find(params[:user_id])
	end

	def horse_params
		params.require(:horse).permit(:name, :sex, :breed_count, :death_count, :tier, :level)
	end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authorize

	def new
		@project = Project.new
		@customers = Customer.all
	end

	def create
		puts params
		@project = Project.new(project_params)
		if @project.save
			redirect_to user_path(current_user.id)
		else
			redirect_to user_path(current_user.id)
		end
	end

	private

	def project_params
		params.require(:project).permit(:name)
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by username: params[:username]
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to user_path(session[:user_id])
		else
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user.id)
		else
			redirect_to new_user_path
		end
	end

	def show
		@user = User.find(params[:id])
		@tasks = @user.tasks
	end

private

	def user_params
		params.require(:user).permit(:name, :username, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/new.html.erb
<h1>New Customer Creation</h1>

<%= form_for :customer, url: '/customer' do |form| %>

	Customer Name: <%= form.text_field :name %><br>
	Address 1: <%= form.text_field :address_1 %><br>
	Address 2: <%= form.text_field :address_2 %><br>
	Address 3: <%= form.text_field :address_3 %><br>
	City: <%= form.text_field :city %><br>
	State: <%= form.text_field :state %><br>
	Zip: <%= form.text_field :zip %><br>
	Phone 1: <%= form.text_field :phone_1 %><br>
	Phone 2: <%= form.text_field :phone_2 %><br>
	Fax 1: <%= form.text_field :fax_1 %><br>
	Fax 2: <%= form.text_field :fax_2 %><br>
	Email Address: <%= form.text_field :email %><br>
	Website: <%= form.text_field :website %><br>
	<%= form.submit "Submit" %>

<% end %>

app/views/horses/index.html.erb
<h1><%= @user.username %>'s Horses</h1>

<% @horses.each do |horse| %>
	<div class="horse_card">
		<h2><%= horse.name  %></h2>
		Sex: <%= horse.sex %><br>
		Remaining Breed Count: <%= horse.breed_count %><br>
		Total Deaths: <%= horse.death_count %><br>
		Tier: <%= horse.tier %><br>
		Level: <%= horse.level %><br>
	</div>
<% end %>

<%= link_to 'New Horse', new_user_horse_path %>

app/views/horses/new.html.erb
<h1>Add New Horse</h1>

<%= form_for [@user, @horse] do |form| %>

	Name: <%= form.text_field :name %><br>
	Sex: <%= form.text_field :sex %><br>
	Remaining Breed Count: <%= form.text_field :breed_count %><br>
	Total Deaths: <%= form.text_field :death_count %><br>
	Tier: <%= form.text_field :tier %><br>
	Level: <%= form.text_field :level %><br>

	<%= form.submit "Submit" %>

<% end %>

app/views/horses/show.html.erb
<h1><%= @horse.name %>'s Info</h1>

Sex: <%= @horse.sex %><br>
Remaining Breed Count: <%= @horse.breed_count %><br>
Total Deaths: <%= @horse.death_count %><br>
Tier: <%= @horse.tier %><br>
Level: <%= @horse.level %><br>

<%= link_to 'Update', edit_horse_path %> | <%= link_to 'Delete', 'horses#destroy' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	Welcome <%= current_user.username %> | <%= link_to 'Home', user_path(current_user.id) %> | <%= link_to 'New Customer', new_customer_path %> | <%= link_to 'New Project', new_project_path %> | <%= link_to 'New Task', new_task_path %> | <%= link_to 'Logout', '/logout' %>
<% else %>
	<%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/users/new' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/projects/new.html.erb
<h1>New Project Creation</h1>

<%= form_for :project, url: projects_path do |form| %>

	Customer: <%= select_tag "customers", options_for_select(@customers.collect {|c| [c['name'], c['id']]}) %>
	Project Name: <%= form.text_field :name %>

	<%= form.submit "Submit" %>

<% end %>

app/views/users/new.html.erb
<h1>New User Signup</h1>

<%= form_for :user, url: '/users' do |form| %>

	Name: <%= form.text_field :name %>
	Username: <%= form.text_field :username %>
	Password: <%= form.password_field :password %>
	Password Confirmation: <%= form.password_field :password_confirmation %>
	<%= form.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Tasks</h1>

<table class="task_table">
	<tr>
		<th>Project Name</th>
		<th>Description</th>
		<th>Duration</th>
	</tr>
</table>

<% @tasks.each do |task| %>
	<td><%= task.project %></td>
<% end %>